services:
  perlite:
    image: sec77/perlite:test
    container_name: perlite-test
    env_file:
      - path: .env
        required: false
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro

  web:
    image: nginx:stable
    container_name: perlite_web-test      
    ports:
      - 80:80 
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro   
    depends_on:
      - perlite

