services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - ${NOTES_PATH:-./perlite/Demo}:/var/www/perlite/Notes:ro
    environment:
      NOTES_PATH: Notes

  web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

